# Generated by Django 5.1.4 on 2024-12-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_price_productattribute_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
