# Generated by Django 5.1.4 on 2024-12-11 11:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
