# Generated by Django 4.2.17 on 2024-12-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rasaproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rasaproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rasaproduct',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='rasaproduct',
            name='stock',
        ),
        migrations.AddField(
            model_name='rasaproduct',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rasaproduct',
            name='atr_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rasaproduct',
            name='ctg_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rasaproduct',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
